version: "3"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py collectstatic --no-input; python3 manage.py migrate; uvicorn mysite.asgi:comp_app --port 8000 --host 0.0.0.0 --reload'
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
    volumes:
      - static:/app/static
      - .:/app/.
    depends_on:
      - db
    restart: on-failure

  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - app
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/var/www/app/static
    ports:
      - "127.0.0.1:8000:8000"


volumes:
  postgresql-data:
  static:
